### PR TITLE
Fix update of expired items

### LINKED ISSUE #123: Strange issue with OnEviction/OnInsertion hooks
It seems under some circumstances single key can be present in cache twice, or at least have a duplicate in expiration queue.

It happens like this:

1. Some keys get added to cache, some get updated to extend their TTL.
2. I dump cache content periodically and see item will be valid, for example, for 10 more seconds.
3. After, for example, 5 seconds OnEviction hook fires for that element.
4. I prolong key for 10 more seconds immediately.
5. Apparently some "lost" key gets prolonged and early OnEviction happens again even tho Item in cache is supposed to expire later.

It feels like in some place which works with expiration queue is not synchronized with storage update and/or duplicate item gets into expiration queue.

I'm using v3.1.1. Unfortunately, that's as much details I can provide, I triggered this issue only in prod environment and didn't managed to reproduce it locally.

### PR DESCRIPTION
**Pull request by Snawoot**
Fix #123 

Extends `get` method to return expired items to `set` method in order to avoid second insertion into expiration queue.

### CODE REVIEW

File: cache_test.go [hunk 1]
```diff
@@ -1212,3 +1212,29 @@ func addToCache(c *Cache[string, string], ttl time.Duration, keys ...string) {
 		c.items.expQueue.push(elem)
 	}
 }
+
+func TestUpdateExpired(t *testing.T) {
```
Comment (davseby) [inline cache_test.go]: This is not how we write unit tests. The test cases should be incorporated into the functions named after the methods that were changed.

File: cache.go [hunk 2]
```diff
@@ -176,14 +176,14 @@ func (c *Cache[K, V]) set(key K, value V, ttl time.Duration) *Item[K, V] {
 // It returns nil if the item is not found or is expired.
 // Not safe for concurrent use by multiple goroutines without additional
 // locking.
-func (c *Cache[K, V]) get(key K, touch bool) *list.Element {
+func (c *Cache[K, V]) get(key K, touch bool, expiredToo bool) *list.Element {
```
Comment (davseby) [inline cache.go]: Something like `includeExpired` would be better.

**Review by davseby — COMMENTED** [review]
Thanks for the contribution.

Providing some feedback, however hadn't had the time to investigate this issue thoroughly, will need to come back and re-check this.

File: cache_test.go (hunk 1 above)
Comment (Snawoot) [reply cache_test.go]: To be honest I don't see much value in this test at all, it's too specific. But this test was crucial for me to reproduce issue I was suspecting and validate solution. Should I relocate it or should I just drop it?

File: cache.go (hunk 2 above)
Comment (Snawoot) [reply cache.go]: Changed.

File: cache_test.go (hunk 1 above)
Comment (davseby) [reply cache_test.go]: `Test_Cache_set` should be expanded to include a test for overwriting an expired item.

Comment (Snawoot) [reply cache_test.go]: Done

**Review by swithek — APPROVED** [review]

**Comment by swithek** [comment]
Thank you for your contribution @Snawoot and sorry for the long wait :pray:
